### ISSUE TITLE
'CFURLCreateStringByAddingPercentEscapes' is deprecated in iOS 9.0

### ISSUE THREAD

**Issue by sneakybVer** [tweetdeck-archive/TDOAuth#16]
'CFURLCreateStringByAddingPercentEscapes' is deprecated: first deprecated in iOS 9.0 - Use [NSString stringByAddingPercentEncodingWithAllowedCharacters:] instead, which always uses the recommended UTF-8 encoding, and which encodes for a specific URL component or subcomponent (since each URL component or subcomponent has different rules for what characters are valid).

**Comment by charlesxsh** [comment]
I fixed that
#define TDPCEN(s) \
      ([[s description] stringByAddingPercentEncodingWithAllowedCharacters:[[NSCharacterSet characterSetWithCharactersInString:@"!*'();:@&=+$,/?%#[] "] invertedSet]]) @sneakybVer

**Comment by mxcl** [comment]
Merged.
