### ISSUE TITLE
Can you publish 1.1.4 podspec?

### ISSUE THREAD

**Issue by dbgrandi** [tweetdeck-archive/TDOAuth#22]
Currently, we have to pin our Podfile to 1.1.2 (due to an encoding issue in 1.1.3) or override `TDOAuth.podspec` locally. Would be nice to just use the published 1.1.4 version.

**Comment by mxcl** [comment]
Sorry, done.

FYI, you can specify the git-tag you need in your `Podfile`, though obviously, better to report the omission like you did, so: many thanks.

**Comment by dbgrandi** [comment]
Thank you! 😄
